// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var $, AboutView, Backbone, JST, _ref;
  $ = require("jquery");
  Backbone = require("backbone");
  JST = require("JST");
  return AboutView = (function(_super) {
    __extends(AboutView, _super);

    function AboutView() {
      _ref = AboutView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AboutView.prototype.render = function() {
      $("#content").html(JST.about());
      $('[data-role="content"]').trigger('create');
      return this;
    };

    return AboutView;

  })(Backbone.View);
});
