// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var $, Backbone, HomeView, JST, Programs, _ref;
  $ = require("jquery");
  Backbone = require("backbone");
  Programs = require("collections/Programs");
  JST = require("JST");
  return HomeView = (function(_super) {
    __extends(HomeView, _super);

    function HomeView() {
      _ref = HomeView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HomeView.prototype.render = function() {
      this.programs = new Programs;
      $("#content").html(JST.home({
        programs: this.programs.toJSON()
      }));
      $('[data-role="content"]').trigger('create');
      return this;
    };

    return HomeView;

  })(Backbone.View);
});
