// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var $, Backbone, JST, ProgramView, Programs;
  $ = require("jquery");
  Backbone = require("backbone");
  JST = require("JST");
  Programs = require("collections/Programs");
  require('jqueryconsole');
  require('rte');
  require('katra');
  require('kc');
  return ProgramView = (function(_super) {
    __extends(ProgramView, _super);

    function ProgramView(id) {
      this.id = parseInt(id, 10);
    }

    ProgramView.prototype.render = function() {
      var programs,
        _this = this;
      programs = new Programs;
      this.program = programs.get(this.id);
      return $.get("bas/" + this.program.get('source'), function(data) {
        var parse;
        $("#content").html(JST.program({
          program: _this.program.toJSON()
        }));
        $('[data-role="content"]').trigger('create');
        parse = function() {
          return katra.parse(data);
        };
        return setTimeout(parse, 1);
      });
    };

    return ProgramView;

  })(Backbone.View);
});
