// Generated by CoffeeScript 1.6.3
require.config({
  paths: {
    jquery: "vendor/jquery-2.0.3.min",
    jquerymobile: "vendor/jquery.mobile-1.3.2.min",
    underscore: "vendor/lodash.underscore.min",
    backbone: "vendor/backbone-min",
    katra: "lib/katra",
    kc: "lib/kc"
  },
  shim: {
    backbone: {
      deps: ["underscore", "jquery"],
      exports: "Backbone"
    }
  }
});

define(function(require) {
  var $, Backbone, Router;
  $ = require("jquery");
  Backbone = require("backbone");
  Router = require("Router");
  $(document).on("mobileinit", function() {
    $.mobile.linkBindingEnabled = false;
    return $.mobile.hashListeningEnabled = false;
  });
  return require(["jquerymobile"], function() {
    return this.router = new Router();
  });
});
