// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var $, AboutView, Backbone, HomeView, ProgramView, ReplView, Router, _ref;
  $ = require("jquery");
  Backbone = require("backbone");
  HomeView = require("views/HomeView");
  ReplView = require("views/ReplView");
  AboutView = require("views/AboutView");
  ProgramView = require("views/ProgramView");
  return Router = (function(_super) {
    __extends(Router, _super);

    function Router() {
      _ref = Router.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Router.prototype.homeView = null;

    Router.prototype.replView = null;

    Router.prototype.aboutView = null;

    Router.prototype.progView = null;

    Router.prototype.routes = {
      "": "homeAction",
      "repl": "replAction",
      "about": "aboutAction",
      "prog/:id": "progAction"
    };

    Router.prototype.initialize = function() {
      return Backbone.history.start();
    };

    Router.prototype.homeAction = function() {
      if (this.homeView == null) {
        this.homeView = new HomeView;
      }
      return this.homeView.render();
    };

    Router.prototype.replAction = function() {
      if (this.replView == null) {
        this.replView = new ReplView;
      }
      return this.replView.render();
    };

    Router.prototype.aboutAction = function() {
      if (this.aboutView == null) {
        this.aboutView = new AboutView;
      }
      return this.aboutView.render();
    };

    Router.prototype.progAction = function(id) {
      this.progView = new ProgramView(id);
      return this.progView.render();
    };

    return Router;

  })(Backbone.Router);
});
