// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var $, Backbone, Program, _ref;
  $ = require("jquery");
  Backbone = require("backbone");
  return Program = (function(_super) {
    __extends(Program, _super);

    function Program() {
      _ref = Program.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return Program;

  })(Backbone.Model);
});
