// Generated by CoffeeScript 1.6.3
define(function(require) {
  var JST, _;
  _ = require("underscore");
  return JST = {
    home: _.template("<ul data-role=\"listview\" data-ajax=\"false\" data-inset=\"true\" data-theme=\"a\">\n<li data-role=\"list-divider\">Games</li>\n<% _.each(programs, function(program) { %>\n    <li>\n        <a href=\"#prog/<%= program.id %>\">\n          <%= program.name %>\n        </a>\n    </li>\n<% }); %>\n</ul>"),
    program: _.template("<div class=\"console\"></div>\n<script>\nkatra.command.cls();//  reset the console\n</script>"),
    repl: _.template("<div class=\"console\"></div>\n<script>\nkatra.command.cls();//  reset the console\n</script>"),
    about: _.template("<img src=\"images/Icon_Android96.png\" /><p>\n<blockquote cite=\"http://darkoverlordofdata.com/katra\">Katra is a basic language interpreter\n    written in coffee-script and using\n    <a href=http://zaach.github.io/jison/>Jison</a>.\n</p><p>Katra has one goal -\n    to run StarTrek.bas games from the golden age of basic programming.</blockquote>\n</p>\n<br />\n<strong><pre>\n\n                 ------*------\n  -------------  `---  ------'\n  `-------- --'    / /\n       \\\\-------  --\n       '-----------'\n</pre></strong>")
  };
});
